# Generated by Django 5.2 on 2025-04-21 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteriamovil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='account_type',
            field=models.CharField(default='usuario', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='lastname',
            field=models.CharField(default='lastname', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='password', max_length=255),
            preserve_default=False,
        ),
    ]
