# Generated by Django 5.2 on 2025-04-21 03:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteriamovil', '0002_usuario_account_type_usuario_lastname_usuario_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=255, verbose_name='Nombre')),
                ('correo_cliente', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('contraseña_cliente', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('direccion_cliente', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono_cliente', models.BigIntegerField(verbose_name='Teléfono')),
                ('fecha_registro', models.DateField(verbose_name='Fecha de registro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_product', models.CharField(max_length=255, verbose_name='Nombre')),
                ('descripcion_product', models.TextField(verbose_name='Descripción')),
                ('precio_product', models.PositiveIntegerField(verbose_name='Precio')),
                ('tipo_product', models.CharField(max_length=255, verbose_name='Tipo')),
                ('imagen_product', models.BinaryField(blank=True, null=True, verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_promocion', models.CharField(max_length=255, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Inicio')),
                ('fecha_termino', models.DateField(verbose_name='Término')),
                ('imagen_promocion', models.BinaryField(blank=True, null=True, verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disp', models.IntegerField(verbose_name='Cantidad disponible')),
                ('unidad_medida', models.CharField(max_length=2, verbose_name='Unidad de medida')),
                ('fecha_actualizacion', models.DateField(verbose_name='Fecha de actualización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='usuario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='account_type',
            field=models.CharField(max_length=50, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='lastname',
            field=models.CharField(max_length=255, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Contraseña'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pedido', models.DateField(verbose_name='Fecha')),
                ('total_pedido', models.CharField(max_length=255, verbose_name='Total')),
                ('estado_pedido', models.CharField(max_length=255, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='cafeteriamovil.client')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField(verbose_name='Comentarios')),
                ('calificacion', models.CharField(max_length=255, verbose_name='Calificación')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='cafeteriamovil.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='cafeteriamovil.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='stock_stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='cafeteriamovil.stock'),
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('subtotal', models.PositiveIntegerField(verbose_name='Subtotal')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cafeteriamovil.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_pedido', to='cafeteriamovil.product')),
            ],
            options={
                'unique_together': {('order', 'product')},
            },
        ),
    ]
