# Generated by Django 5.2 on 2025-04-21 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteriamovil', '0003_client_product_promotions_stock_usuario_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('lastname', models.CharField(max_length=255, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('password', models.CharField(max_length=255, verbose_name='Contraseña')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to='cafeteriamovil.account_detail')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock_stock',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='fecha_pedido',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='estado_pedido',
            new_name='order_status',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_pedido',
            new_name='order_total',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='cantidad',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='descripcion_product',
            new_name='product_desc',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='nombre_product',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='precio_product',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='promotions',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='promotions',
            old_name='fecha_termino',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='promotions',
            old_name='titulo_promocion',
            new_name='promotion_title',
        ),
        migrations.RenameField(
            model_name='promotions',
            old_name='imagen_promocion',
            new_name='promotional_image',
        ),
        migrations.RenameField(
            model_name='promotions',
            old_name='fecha_inicio',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tipo_product',
        ),
        migrations.AddField(
            model_name='product',
            name='promotion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='promocion', to='cafeteriamovil.promotions'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock_product',
            field=models.PositiveIntegerField(default=1, verbose_name='Stock'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_producto', to='cafeteriamovil.product_detail'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='cafeteriamovil.user'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reseñas', to='cafeteriamovil.user'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
    ]
