# Generated by Django 5.2 on 2025-04-22 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteriamovil', '0004_account_detail_product_detail_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ID',
            field=models.CharField(default='hola', max_length=255, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
