# Generated by Django 5.2 on 2025-04-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteriamovil', '0004_account_detail_product_detail_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='promotional_image',
            field=models.ImageField(blank=True, null=True, upload_to='statics/img/'),
        ),
    ]
