# Generated by Django 5.2 on 2025-04-23 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteriamovil', '0005_alter_promotions_promotional_image'),
        ('cafeteriamovil', '0005_user_id'),
    ]

    operations = [
    ]
