# Generated by Django 5.2 on 2025-04-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteriamovil', '0006_merge_20250422_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotions',
            name='promotional_image',
            field=models.BinaryField(blank=True, null=True, verbose_name='Imagen'),
        ),
    ]
