# Generated by Django 5.2 on 2025-05-01 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteriamovil', '0007_alter_promotions_promotional_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imagen_product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promotion',
        ),
        migrations.RemoveField(
            model_name='user',
            name='ID',
        ),
    ]
