# Generated by Django 5.2 on 2025-05-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteriamovil', '0008_remove_product_imagen_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotions',
            name='promotional_image',
        ),
        migrations.AddField(
            model_name='product',
            name='imagen_product',
            field=models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen'),
        ),
    ]
